version: "3.9"
services:
    zookeeper:
        mem_limit: 500000000
        container_name: zookeeper
        image: 'bitnami/zookeeper:latest'
        networks:
            - app-tier
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        mem_limit: 1000000000
        depends_on:
            - zookeeper
        container_name: kafka-server
        image: 'bitnami/kafka:latest'
        networks:
            - app-tier
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        healthcheck:
            test:
                ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
            interval: 30s
            timeout: 10s
            retries: 4
    redis:
        mem_limit: 50000000
        container_name: redis
        image: 'redis:latest'
        networks:
            - app-tier
    utxo-tracker:
        mem_limit: 500000000
        image: luivatra/utxotracker:latest
        container_name: utxo-tracker
        depends_on:
            - redis
            - kafka
        networks:
            - app-tier
        env_file: config.env
    pool-resolver:
        mem_limit: 500000000
        image: luivatra/poolresolver:latest
        container_name: pool-resolver
        depends_on:
            - kafka
        networks:
            - app-tier
        env_file: config.env
    amm-executor:
        mem_limit: 500000000
        image: luivatra/ammexecutor:latest
        container_name: amm-executor
        depends_on:
            - kafka
        networks:
            - app-tier
        env_file: config.env
networks:
    app-tier: {}