version: "3.9"
services:
  ergo-mixer:
    container_name: 'Ergo-mixer'
    image: 'luivatra/mixer:latest-arm64'
    ports:
      - '127.0.0.1:9000:9000'
    networks:
      - ergo-net
    volumes:
      - ergo-mixer-data:/home/ergo/ergoMixer
networks:
  ergo-net:
    external: true
    name: 'ergo-net'
volumes:
  ergo-mixer-data: